# Generated by Django 5.0.3 on 2024-03-05 12:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipeandreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeAndReview',
            new_name='RatingAndReview',
        ),
    ]
